/**
 * Steam Direct URI & Desktop Game Launcher Utility
 * 
 * Provides client-side and server-backed direct Steam launching:
 * 1. Direct browser protocol invocation: steam://rungameid/<appId>
 * 2. Host-level execution via /api/steam/launch-game (native steam, flatpak steam, xdg-open)
 * 3. Desktop shortcut creation (.desktop for Linux, bash launcher script, Windows .url)
 */

export interface LaunchGameResult {
  success: boolean;
  message: string;
  steamUri: string;
  dispatchedCommand?: string;
  method: 'browser_uri' | 'server_dispatch' | 'download_script';
}

/**
 * Dispatches a direct Steam URI launch command for an AppID
 */
export async function launchSteamGame(appId: number, gameName?: string): Promise<LaunchGameResult> {
  const steamUri = `steam://rungameid/${appId}`;

  // 1. First trigger client-side browser URI protocol handler (instant Steam client focus)
  try {
    const link = document.createElement('a');
    link.href = steamUri;
    link.rel = 'noreferrer';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (err) {
    console.warn('Browser direct URI navigation failed, attempting server dispatch...', err);
  }

  // 2. Also dispatch to backend API if host is running locally
  try {
    const response = await fetch('/api/steam/launch-game', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ appId, gameName }),
    });

    if (response.ok) {
      const data = await response.json();
      return {
        success: true,
        message: data.message || `Dispatched Steam launch for ${gameName || `App ${appId}`}`,
        steamUri,
        dispatchedCommand: data.dispatchedCommand,
        method: data.executionMethod === 'browser_uri' ? 'browser_uri' : 'server_dispatch',
      };
    }
  } catch {
    // API not reachable or running in remote container — browser protocol was already triggered
  }

  return {
    success: true,
    message: `Launched ${gameName || `App ${appId}`} via Steam URI (${steamUri})`,
    steamUri,
    method: 'browser_uri',
  };
}

/**
 * Downloads a Linux .desktop shortcut file for direct desktop launching
 */
export function downloadLinuxDesktopShortcut(appId: number, gameName: string, iconUrl?: string): void {
  const safeName = gameName.replace(/[^a-zA-Z0-9_\- ]/g, '').trim() || `Game_${appId}`;
  const desktopContent = `[Desktop Entry]
Name=${gameName}
Comment=Launch ${gameName} via Steam
Exec=steam steam://rungameid/${appId}
Icon=steam_icon_${appId}
Terminal=false
Type=Application
Categories=Game;
Keywords=steam;game;proton;
`;

  const blob = new Blob([desktopContent], { type: 'application/x-desktop;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName}.desktop`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Downloads a standalone Linux bash script to run the game with current launch options
 */
export function downloadBashLauncherScript(appId: number, gameName: string, launchOptions?: string): void {
  const safeName = gameName.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_');
  const filename = `launch_${safeName || 'game'}_${appId}.sh`;

  const content = `#!/usr/bin/env bash
# ==============================================================================
# Direct Steam Launcher Script for: ${gameName} (AppID: ${appId})
# Generated by Proton Launch Options Manager
# ==============================================================================

echo "========================================================"
echo " Launching: ${gameName} (AppID: ${appId})"
${launchOptions ? `echo " Launch Options: ${launchOptions}"` : ''}
echo "========================================================"

# Check if Steam is running; start Steam or send rungameid
if command -v steam >/dev/null 2>&1; then
    echo "[+] Dispatching via Native Steam..."
    steam "steam://rungameid/${appId}" &
elif flatpak list --app | grep -q "com.valvesoftware.Steam"; then
    echo "[+] Dispatching via Flatpak Steam..."
    flatpak run com.valvesoftware.Steam "steam://rungameid/${appId}" &
elif command -v xdg-open >/dev/null 2>&1; then
    echo "[+] Dispatching via xdg-open..."
    xdg-open "steam://rungameid/${appId}" &
else
    echo "[!] Steam client binary not found in standard PATH."
    echo "    Opening steam://rungameid/${appId}"
fi

echo "[✓] Launch signal sent to Steam."
`;

  const blob = new Blob([content], { type: 'text/x-sh;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
